FROM node:alpine

WORKDIR /usr/src/app

COPY ./* /usr/src/app/

RUN apk add --update --no-cache \
  make \
  g++ \
  automake \
  autoconf \
  libtool \
  nasm \
  libjpeg-turbo-dev
RUN npm install jpegtran-bin

RUN apt update && apt install -y zip

RUN npm install && npm run build

RUN zip -r dist.zip dist
