FROM node:16

RUN mkdir -p /app \
 && chown -R node:node /app

WORKDIR /app

COPY --chown=node:node . .

USER node

RUN yarn && yarn add moment && yarn add vis-util && npm run build-dev --prod --build-optimizer

RUN npm run compress:brotli
# RUN npm run compress:gzip

WORKDIR /app/dist
RUN npm install --production

EXPOSE 3004
CMD ["npm", "run", "serve:prod"]
