FROM node:10

RUN useradd -ms /bin/bash appuser \
    && mkdir -p /app \
    && chown -R appuser:appuser /app

WORKDIR /app

COPY --chown=appuser:appuser . .

USER appuser

RUN yarn && yarn add moment && yarn add vis-util && npm run build-dev --prod --build-optimizer

RUN npm run compress:brotli
# RUN npm run compress:gzip

WORKDIR /app/dist
RUN npm install --production

EXPOSE 3004
CMD ["npm", "run", "serve:prod"]
